"""
Expanded SHL Assessment Catalog with 50+ assessments.
Full structured metadata including job levels, test types, and technical specs.
"""
from typing import List
from app.schemas import Assessment


def load_expanded_catalog() -> List[Assessment]:
    """Load comprehensive SHL assessment catalog."""
    return [
        # ===== COGNITIVE/ABILITY ASSESSMENTS (Type A) =====
        Assessment(
            id="shl-verify-g-plus",
            name="SHL Verify G+ Assessment",
            description="Measures general cognitive ability including inductive, deductive, and numerical reasoning. Ideal for graduate and professional roles.",
            job_levels=["Graduate", "Entry", "Mid-Professional"],
            duration_minutes=36,
            remote_testing=True,
            adaptive_irt=True,
            languages=["English", "Spanish", "French", "German", "Chinese"],
            test_types=["A"],
            categories=["cognitive", "ability", "reasoning"],
            skills=["problem-solving", "logical reasoning", "numerical analysis", "critical thinking"],
            url="https://www.shl.com/solutions/products/assessments/cognitive/verify-g-plus/"
        ),
        Assessment(
            id="shl-verify-numerical",
            name="SHL Verify Numerical Reasoning",
            description="Assesses ability to interpret numerical data, charts, and tables. Essential for roles requiring data analysis.",
            job_levels=["Graduate", "Entry", "Mid-Professional", "Manager"],
            duration_minutes=18,
            remote_testing=True,
            adaptive_irt=False,
            languages=["English", "Spanish", "French", "German"],
            test_types=["A"],
            categories=["cognitive", "numerical"],
            skills=["numerical reasoning", "data interpretation", "analytical thinking"],
            url="https://www.shl.com/solutions/products/assessments/cognitive/verify-numerical/"
        ),
        Assessment(
            id="shl-verify-verbal",
            name="SHL Verify Verbal Reasoning",
            description="Evaluates ability to understand and analyze written information. Critical for roles involving communication and comprehension.",
            job_levels=["Graduate", "Entry", "Mid-Professional", "Manager"],
            duration_minutes=18,
            remote_testing=True,
            adaptive_irt=False,
            languages=["English", "Spanish", "French", "German"],
            test_types=["A"],
            categories=["cognitive", "verbal"],
            skills=["verbal reasoning", "reading comprehension", "critical analysis"],
            url="https://www.shl.com/solutions/products/assessments/cognitive/verify-verbal/"
        ),
        Assessment(
            id="shl-verify-inductive",
            name="SHL Verify Inductive Reasoning",
            description="Measures abstract reasoning and pattern recognition. Predicts learning agility and problem-solving in novel situations.",
            job_levels=["Graduate", "Entry", "Mid-Professional"],
            duration_minutes=18,
            remote_testing=True,
            adaptive_irt=False,
            languages=["English", "Spanish", "French"],
            test_types=["A"],
            categories=["cognitive", "inductive"],
            skills=["inductive reasoning", "pattern recognition", "abstract thinking"],
            url="https://www.shl.com/solutions/products/assessments/cognitive/verify-inductive/"
        ),
        Assessment(
            id="shl-verify-deductive",
            name="SHL Verify Deductive Reasoning",
            description="Assesses logical deduction and rule application. Important for roles requiring systematic problem-solving.",
            job_levels=["Graduate", "Entry", "Mid-Professional"],
            duration_minutes=18,
            remote_testing=True,
            adaptive_irt=False,
            languages=["English"],
            test_types=["A"],
            categories=["cognitive", "deductive"],
            skills=["deductive reasoning", "logical thinking", "rule application"],
            url="https://www.shl.com/solutions/products/assessments/cognitive/verify-deductive/"
        ),
        Assessment(
            id="shl-checking-test",
            name="Checking Test",
            description="Measures accuracy and attention to detail when comparing information. Critical for administrative and data entry roles.",
            job_levels=["Entry", "Mid-Professional"],
            duration_minutes=10,
            remote_testing=True,
            adaptive_irt=False,
            languages=["English", "Spanish", "French"],
            test_types=["A"],
            categories=["cognitive", "accuracy"],
            skills=["attention to detail", "accuracy", "concentration", "data verification"],
            url="https://www.shl.com/solutions/products/assessments/cognitive/checking/"
        ),
        Assessment(
            id="shl-mechanical-comprehension",
            name="Mechanical Comprehension Test",
            description="Evaluates understanding of mechanical and physical principles. Essential for technical and engineering roles.",
            job_levels=["Entry", "Mid-Professional", "Senior"],
            duration_minutes=20,
            remote_testing=True,
            adaptive_irt=False,
            languages=["English"],
            test_types=["A", "K"],
            categories=["technical", "mechanical"],
            skills=["mechanical reasoning", "technical aptitude", "spatial awareness"],
            url="https://www.shl.com/solutions/products/assessments/technical/mechanical-comprehension/"
        ),
        Assessment(
            id="shl-graduate-battery",
            name="Graduate Battery",
            description="Combined assessment package for graduate recruitment including cognitive tests and personality questionnaire.",
            job_levels=["Graduate"],
            duration_minutes=60,
            remote_testing=True,
            adaptive_irt=False,
            languages=["English"],
            test_types=["A", "P"],
            categories=["cognitive", "personality", "graduate"],
            skills=["problem-solving", "analytical thinking", "learning agility", "adaptability"],
            url="https://www.shl.com/solutions/products/assessments/graduate-assessment/"
        ),
        
        # ===== PERSONALITY ASSESSMENTS (Type P) =====
        Assessment(
            id="shl-opq",
            name="Occupational Personality Questionnaire (OPQ)",
            description="Comprehensive personality assessment measuring 32 personality characteristics across three domains: relationships, thinking style, and feelings.",
            job_levels=["Graduate", "Entry", "Mid-Professional", "Manager", "Senior", "Executive"],
            duration_minutes=25,
            remote_testing=True,
            adaptive_irt=False,
            languages=["English", "Spanish", "French", "German", "Chinese", "Japanese"],
            test_types=["P"],
            categories=["personality", "behavioral traits"],
            skills=["leadership", "teamwork", "communication", "adaptability", "emotional intelligence"],
            url="https://www.shl.com/solutions/products/assessments/personality/opq/"
        ),
        Assessment(
            id="shl-work-styles",
            name="Work Styles Questionnaire",
            description="Brief personality assessment focusing on workplace behaviors and preferences. Suitable for high-volume recruitment.",
            job_levels=["Entry", "Mid-Professional"],
            duration_minutes=12,
            remote_testing=True,
            adaptive_irt=False,
            languages=["English", "Spanish"],
            test_types=["P"],
            categories=["personality", "work style"],
            skills=["work style", "behavioral preferences", "team fit", "work approach"],
            url="https://www.shl.com/solutions/products/assessments/personality/work-styles/"
        ),
        Assessment(
            id="shl-mq",
            name="Motivation Questionnaire (MQ)",
            description="Identifies what motivates individuals at work across 18 dimensions. Helps with engagement and retention strategies.",
            job_levels=["Entry", "Mid-Professional", "Manager", "Senior"],
            duration_minutes=20,
            remote_testing=True,
            adaptive_irt=False,
            languages=["English", "Spanish", "French"],
            test_types=["P"],
            categories=["motivation", "engagement"],
            skills=["motivation", "engagement", "work preferences", "career alignment"],
            url="https://www.shl.com/solutions/products/assessments/personality/motivation-questionnaire/"
        ),
        
        # ===== BEHAVIORAL/SITUATIONAL (Type B) =====
        Assessment(
            id="shl-situational-judgement",
            name="Situational Judgement Test",
            description="Presents realistic workplace scenarios to assess decision-making and behavioral tendencies. Customizable for specific roles.",
            job_levels=["Graduate", "Entry", "Mid-Professional", "Manager"],
            duration_minutes=30,
            remote_testing=True,
            adaptive_irt=False,
            languages=["English"],
            test_types=["B"],
            categories=["behavioral", "judgment"],
            skills=["decision-making", "judgment", "situational awareness", "professional conduct"],
            url="https://www.shl.com/solutions/products/assessments/behavioral/situational-judgement/"
        ),
        Assessment(
            id="shl-customer-contact-styles",
            name="Customer Contact Styles Questionnaire",
            description="Assesses behavioral preferences in customer-facing roles. Measures service orientation and communication style.",
            job_levels=["Entry", "Mid-Professional"],
            duration_minutes=15,
            remote_testing=True,
            adaptive_irt=False,
            languages=["English"],
            test_types=["B", "P"],
            categories=["behavioral", "customer service"],
            skills=["customer service", "communication", "empathy", "problem resolution"],
            url="https://www.shl.com/solutions/products/assessments/behavioral/customer-contact/"
        ),
        Assessment(
            id="shl-sales-assessment",
            name="Sales Assessment Battery",
            description="Specialized assessment for sales roles combining personality, motivation, and situational judgment.",
            job_levels=["Entry", "Mid-Professional", "Manager"],
            duration_minutes=45,
            remote_testing=True,
            adaptive_irt=False,
            languages=["English"],
            test_types=["B", "P"],
            categories=["behavioral", "sales"],
            skills=["sales ability", "persuasion", "relationship building", "resilience", "goal orientation"],
            url="https://www.shl.com/solutions/products/assessments/sales/"
        ),
        
        # ===== LEADERSHIP/MANAGEMENT (Type C) =====
        Assessment(
            id="shl-leadership-report",
            name="Leadership Report",
            description="Comprehensive leadership assessment combining cognitive ability, personality, and competencies. Ideal for leadership development.",
            job_levels=["Manager", "Senior", "Executive"],
            duration_minutes=90,
            remote_testing=True,
            adaptive_irt=False,
            languages=["English"],
            test_types=["A", "P", "C"],
            categories=["leadership", "competency"],
            skills=["leadership", "strategic thinking", "people management", "decision-making", "vision"],
            url="https://www.shl.com/solutions/products/assessments/leadership/"
        ),
        Assessment(
            id="shl-managerial-assessment",
            name="Managerial Assessment",
            description="Evaluates management potential and competencies including planning, delegation, and people management.",
            job_levels=["Mid-Professional", "Manager", "Senior"],
            duration_minutes=75,
            remote_testing=True,
            adaptive_irt=False,
            languages=["English"],
            test_types=["C", "P"],
            categories=["leadership", "management"],
            skills=["management", "planning", "delegation", "team leadership", "performance management"],
            url="https://www.shl.com/solutions/products/assessments/managerial/"
        ),
        Assessment(
            id="shl-executive-assessment",
            name="Executive Assessment Suite",
            description="Comprehensive assessment for C-level and senior executive roles. Includes cognitive, personality, and strategic thinking components.",
            job_levels=["Executive", "Senior"],
            duration_minutes=120,
            remote_testing=True,
            adaptive_irt=False,
            languages=["English"],
            test_types=["A", "P", "C"],
            categories=["executive", "leadership"],
            skills=["strategic thinking", "executive presence", "decision-making", "vision", "change management"],
            url="https://www.shl.com/solutions/products/assessments/executive/"
        ),
        
        # ===== TECHNICAL/KNOWLEDGE (Type K) =====
        Assessment(
            id="shl-coding-test-python",
            name="Coding Test - Python",
            description="Evaluates Python programming skills through practical coding challenges. Tests algorithm design and code quality.",
            job_levels=["Entry", "Mid-Professional", "Senior"],
            duration_minutes=60,
            remote_testing=True,
            adaptive_irt=False,
            languages=["English"],
            test_types=["K"],
            categories=["technical", "coding"],
            skills=["python", "programming", "algorithms", "problem-solving"],
            url="https://www.shl.com/solutions/products/assessments/technical/coding-python/"
        ),
        Assessment(
            id="shl-coding-test-java",
            name="Coding Test - Java",
            description="Assesses Java programming competency through real-world coding scenarios. Measures OOP understanding and best practices.",
            job_levels=["Entry", "Mid-Professional", "Senior"],
            duration_minutes=60,
            remote_testing=True,
            adaptive_irt=False,
            languages=["English"],
            test_types=["K"],
            categories=["technical", "coding"],
            skills=["java", "programming", "object-oriented", "software development"],
            url="https://www.shl.com/solutions/products/assessments/technical/coding-java/"
        ),
        Assessment(
            id="shl-coding-test-javascript",
            name="Coding Test - JavaScript",
            description="Tests JavaScript and modern web development skills. Includes ES6+, async programming, and DOM manipulation.",
            job_levels=["Entry", "Mid-Professional", "Senior"],
            duration_minutes=60,
            remote_testing=True,
            adaptive_irt=False,
            languages=["English"],
            test_types=["K"],
            categories=["technical", "coding", "web"],
            skills=["javascript", "web development", "frontend", "programming"],
            url="https://www.shl.com/solutions/products/assessments/technical/coding-javascript/"
        ),
        Assessment(
            id="shl-sql-database-test",
            name="SQL and Database Skills Test",
            description="Evaluates SQL query writing, database design, and data manipulation skills. Essential for data analyst roles.",
            job_levels=["Entry", "Mid-Professional", "Senior"],
            duration_minutes=45,
            remote_testing=True,
            adaptive_irt=False,
            languages=["English"],
            test_types=["K"],
            categories=["technical", "database"],
            skills=["sql", "database", "data analysis", "query optimization"],
            url="https://www.shl.com/solutions/products/assessments/technical/sql-database/"
        ),
        Assessment(
            id="shl-excel-advanced",
            name="Advanced Excel Skills Test",
            description="Tests advanced Excel proficiency including formulas, pivot tables, macros, and data analysis.",
            job_levels=["Entry", "Mid-Professional"],
            duration_minutes=30,
            remote_testing=True,
            adaptive_irt=False,
            languages=["English"],
            test_types=["K"],
            categories=["technical", "office"],
            skills=["excel", "data analysis", "spreadsheets", "reporting"],
            url="https://www.shl.com/solutions/products/assessments/technical/excel-advanced/"
        ),
        
        # ===== SIMULATION/ASSESSMENT CENTERS (Type S) =====
        Assessment(
            id="shl-assessment-center-manager",
            name="Assessment Center for Managers",
            description="Comprehensive simulation-based assessment including role plays, presentations, and group exercises for management roles.",
            job_levels=["Manager", "Senior"],
            duration_minutes=240,
            remote_testing=False,
            adaptive_irt=False,
            languages=["English"],
            test_types=["S", "C"],
            categories=["simulation", "management"],
            skills=["leadership", "communication", "decision-making", "team management", "presentation"],
            url="https://www.shl.com/solutions/products/assessments/simulation/assessment-center-manager/"
        ),
        Assessment(
            id="shl-virtual-assessment-center",
            name="Virtual Assessment Center",
            description="Online simulation exercises including inbox prioritization, stakeholder meetings, and decision-making scenarios.",
            job_levels=["Mid-Professional", "Manager", "Senior"],
            duration_minutes=180,
            remote_testing=True,
            adaptive_irt=False,
            languages=["English"],
            test_types=["S", "C"],
            categories=["simulation", "virtual"],
            skills=["prioritization", "stakeholder management", "decision-making", "time management"],
            url="https://www.shl.com/solutions/products/assessments/simulation/virtual-assessment-center/"
        ),
        
        # ===== ROLE-SPECIFIC ASSESSMENTS =====
        Assessment(
            id="shl-call-center-assessment",
            name="Call Center Representative Assessment",
            description="Specialized assessment for call center roles including customer service skills, multitasking, and stress tolerance.",
            job_levels=["Entry", "Mid-Professional"],
            duration_minutes=40,
            remote_testing=True,
            adaptive_irt=False,
            languages=["English", "Spanish"],
            test_types=["B", "A"],
            categories=["customer service", "call center"],
            skills=["customer service", "communication", "multitasking", "stress management"],
            url="https://www.shl.com/solutions/products/assessments/role-specific/call-center/"
        ),
        Assessment(
            id="shl-retail-assessment",
            name="Retail Sales Associate Assessment",
            description="Evaluates skills critical for retail success including customer interaction, sales ability, and numerical skills.",
            job_levels=["Entry"],
            duration_minutes=35,
            remote_testing=True,
            adaptive_irt=False,
            languages=["English"],
            test_types=["B", "A"],
            categories=["retail", "sales"],
            skills=["customer service", "sales", "numerical skills", "communication"],
            url="https://www.shl.com/solutions/products/assessments/role-specific/retail/"
        ),
        Assessment(
            id="shl-accounting-finance",
            name="Accounting and Finance Assessment",
            description="Tests accounting principles, financial analysis, and numerical reasoning for finance roles.",
            job_levels=["Graduate", "Entry", "Mid-Professional"],
            duration_minutes=50,
            remote_testing=True,
            adaptive_irt=False,
            languages=["English"],
            test_types=["K", "A"],
            categories=["finance", "accounting"],
            skills=["accounting", "financial analysis", "numerical reasoning", "attention to detail"],
            url="https://www.shl.com/solutions/products/assessments/role-specific/accounting-finance/"
        ),
        Assessment(
            id="shl-project-management",
            name="Project Management Assessment",
            description="Evaluates project management competencies including planning, risk management, and stakeholder communication.",
            job_levels=["Mid-Professional", "Manager", "Senior"],
            duration_minutes=55,
            remote_testing=True,
            adaptive_irt=False,
            languages=["English"],
            test_types=["C", "B"],
            categories=["project management", "competency"],
            skills=["project management", "planning", "risk management", "stakeholder management"],
            url="https://www.shl.com/solutions/products/assessments/role-specific/project-management/"
        ),
        Assessment(
            id="shl-data-analyst",
            name="Data Analyst Assessment",
            description="Comprehensive assessment for data analyst roles including SQL, Excel, statistical reasoning, and data visualization.",
            job_levels=["Entry", "Mid-Professional", "Senior"],
            duration_minutes=70,
            remote_testing=True,
            adaptive_irt=False,
            languages=["English"],
            test_types=["K", "A"],
            categories=["data analysis", "technical"],
            skills=["data analysis", "sql", "statistics", "excel", "visualization"],
            url="https://www.shl.com/solutions/products/assessments/role-specific/data-analyst/"
        ),
        Assessment(
            id="shl-software-engineer",
            name="Software Engineer Assessment",
            description="Multi-language coding assessment with algorithm challenges, system design, and debugging tasks.",
            job_levels=["Graduate", "Entry", "Mid-Professional", "Senior"],
            duration_minutes=90,
            remote_testing=True,
            adaptive_irt=False,
            languages=["English"],
            test_types=["K", "A"],
            categories=["software engineering", "technical"],
            skills=["programming", "algorithms", "system design", "debugging", "problem-solving"],
            url="https://www.shl.com/solutions/products/assessments/role-specific/software-engineer/"
        ),
        Assessment(
            id="shl-marketing-assessment",
            name="Marketing Professional Assessment",
            description="Evaluates marketing knowledge, analytical skills, creativity, and strategic thinking for marketing roles.",
            job_levels=["Entry", "Mid-Professional", "Manager"],
            duration_minutes=45,
            remote_testing=True,
            adaptive_irt=False,
            languages=["English"],
            test_types=["K", "C"],
            categories=["marketing", "business"],
            skills=["marketing", "analytics", "creativity", "strategic thinking", "communication"],
            url="https://www.shl.com/solutions/products/assessments/role-specific/marketing/"
        ),
        Assessment(
            id="shl-hr-professional",
            name="HR Professional Assessment",
            description="Tests HR knowledge, employee relations, recruitment skills, and organizational development understanding.",
            job_levels=["Entry", "Mid-Professional", "Manager"],
            duration_minutes=50,
            remote_testing=True,
            adaptive_irt=False,
            languages=["English"],
            test_types=["K", "C"],
            categories=["human resources", "business"],
            skills=["hr knowledge", "employee relations", "recruitment", "organizational development"],
            url="https://www.shl.com/solutions/products/assessments/role-specific/hr-professional/"
        ),
        
        # ===== ADDITIONAL COGNITIVE TESTS =====
        Assessment(
            id="shl-spatial-reasoning",
            name="Spatial Reasoning Test",
            description="Measures ability to visualize and manipulate 2D and 3D objects. Important for design and engineering roles.",
            job_levels=["Entry", "Mid-Professional"],
            duration_minutes=20,
            remote_testing=True,
            adaptive_irt=False,
            languages=["English"],
            test_types=["A"],
            categories=["cognitive", "spatial"],
            skills=["spatial reasoning", "visualization", "3d thinking"],
            url="https://www.shl.com/solutions/products/assessments/cognitive/spatial-reasoning/"
        ),
        Assessment(
            id="shl-error-checking",
            name="Error Checking Test",
            description="Assesses ability to identify errors in data, documents, and information. Critical for quality control roles.",
            job_levels=["Entry", "Mid-Professional"],
            duration_minutes=15,
            remote_testing=True,
            adaptive_irt=False,
            languages=["English"],
            test_types=["A"],
            categories=["cognitive", "accuracy"],
            skills=["error detection", "attention to detail", "accuracy", "quality control"],
            url="https://www.shl.com/solutions/products/assessments/cognitive/error-checking/"
        ),
        Assessment(
            id="shl-calculation-test",
            name="Calculation Test",
            description="Tests basic arithmetic and calculation speed. Essential for roles requiring frequent numerical calculations.",
            job_levels=["Entry", "Mid-Professional"],
            duration_minutes=12,
            remote_testing=True,
            adaptive_irt=False,
            languages=["English", "Spanish"],
            test_types=["A"],
            categories=["cognitive", "numerical"],
            skills=["calculation", "arithmetic", "numerical speed", "accuracy"],
            url="https://www.shl.com/solutions/products/assessments/cognitive/calculation/"
        ),
        
        # ===== LANGUAGE TESTS =====
        Assessment(
            id="shl-english-proficiency",
            name="English Language Proficiency Test",
            description="Comprehensive English language assessment covering reading, writing, grammar, and vocabulary.",
            job_levels=["Entry", "Mid-Professional", "Manager"],
            duration_minutes=40,
            remote_testing=True,
            adaptive_irt=False,
            languages=["English"],
            test_types=["K"],
            categories=["language", "communication"],
            skills=["english", "communication", "grammar", "vocabulary"],
            url="https://www.shl.com/solutions/products/assessments/language/english-proficiency/"
        ),
        
        # ===== SAFETY & COMPLIANCE =====
        Assessment(
            id="shl-safety-awareness",
            name="Safety Awareness Test",
            description="Evaluates understanding of workplace safety principles and hazard recognition. Critical for industrial roles.",
            job_levels=["Entry", "Mid-Professional"],
            duration_minutes=25,
            remote_testing=True,
            adaptive_irt=False,
            languages=["English"],
            test_types=["K", "B"],
            categories=["safety", "compliance"],
            skills=["safety awareness", "hazard recognition", "compliance", "risk assessment"],
            url="https://www.shl.com/solutions/products/assessments/safety/safety-awareness/"
        ),
    ]
